cadastro/app.py
from flask import Flask
from routes.user import user

app = Flask(__name__)
app.register_blueprint(user)

if __name__ == "__main__":
    app.run(debug=True)

cadastro/routes/user.py
from flask import Blueprint, render_template, request, flash
from Db.database import *
import sqlite3

user = Blueprint('user',__name__)

@user.route("/")
def home():
    return render_template("index.html")

@user.route("/registro", methods=["GET","POST"])
def Usuario():
    if request.method == "POST":
        user = request.form["campo1"]
        senha = request.form["campo2"]

        command, param = addUser(user,senha)
        try:
            db = sqlite3.connect("Navigator.db")
            cursor = db.cursor()
            cursor.execute(table_user)
            # Verificar se o usuário já existe
            cursor.execute("SELECT * FROM Usuario WHERE Username = ?", (user,))
            existing_user = cursor.fetchone()
            
            if existing_user:
                flash("Usuário já existe! Escolha outro nome.", "warning")
                print(f"Usuário {user} já existe!")
            else:
                # Criar usuário se não existir
                command, param = addUser(user, senha)
                cursor.execute(command, param)
                db.commit()
                flash("Usuário registrado com sucesso!", "success")
                print(f"Usuário {user} registrado com sucesso!")
        except Exception as e:
            print(f"Error:{e}")
        finally:
            if db:
                db.close()
                print("Conexão fechada com exito!")
    return render_template("user.html")

cadastro/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Principal</title>
</head>
<body>
    <h1>Teste</h1>
    <a href="{{url_for('user.Usuario')}}">Registrar</a>
</body>
</html>

cadastro/templates/user.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Usuario</title>
</head>
<body>
    <h1>Registro de Usuario</h1>
    <form action="/registro" method="POST">
        <label for="campo1">Usuario:</label>
        <input type="text" id="campo1" name="campo1" required>
        <br><br>

        <label for="campo2">Senha:</label>
        <input type="password" id="campo2" name="campo2" required>
        <br><br>

        <button type="submit">Enviar</button>
    </form>
</body>
</html>